In [1]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib
import seaborn

print("Everything works!")

Everything works!

In [4]:
dev_data=pd.read_csv("../data/development_data.csv")
eval_data=pd.read_csv("../data/evaluation_data.csv")
dev_data.head()

,sample_id,age,ethnicity,sex,cg16867657,cg06639320,cg24724428,cg07553761,cg22454769,cg06784991,...,cg17321954,cg17783401,cg26483332,cg22730412,cg14704921,cg12179661,cg16780603,cg00588614,cg13039082,cg16640358
0,GSM990554,79,Caucasian - European,M,0.672001,0.504461,0.331257,0.327287,0.572867,0.309496,...,0.174936,0.094635,0.163394,0.304777,0.093110,0.522947,0.736352,0.262954,0.295386,0.350803
1,GSM990278,46,Hispanic - Mexican,M,0.555411,0.389214,0.160708,0.230875,0.464971,0.223665,...,0.154691,0.043087,0.173311,0.343683,0.029271,0.496056,0.801962,0.291890,0.288421,0.318693
2,GSM990589,78,Caucasian - European,M,0.781318,0.554360,0.337578,0.437668,0.645529,0.309615,...,0.213999,0.089760,0.173368,0.338127,0.066988,0.484525,0.588307,0.276745,0.263589,0.344015
3,GSM990323,46,Hispanic - Mexican,F,0.542491,0.435584,0.228723,0.231709,0.493908,0.245836,...,0.198334,0.121145,0.164312,0.394890,0.044809,0.510717,0.736712,0.287274,0.333076,0.303317
4,GSM990116,59,Hispanic - Mexican,F,0.653190,0.466217,0.208453,0.284740,0.592122,0.239320,...,0.147234,0.035716,0.156062,0.341784,0.024294,NaN,0.828072,0.256653,0.322450,0.370363

In [ ]:
print("Development data shape:", dev_data.shape)
print("Evaluation data shape:", eval_data.shape)

dev_data.info()
dev_data.describe()

Development data shape: (456, 1004)
Evaluation data shape: (100, 1004)
<class 'pandas.DataFrame'>
RangeIndex: 456 entries, 0 to 455
Columns: 1004 entries, sample_id to cg16640358
dtypes: float64(1000), int64(1), str(3)
memory usage: 3.5 MB

,age,cg16867657,cg06639320,cg24724428,cg07553761,cg22454769,cg06784991,cg21572722,cg24079702,cg03032497,...,cg17321954,cg17783401,cg26483332,cg22730412,cg14704921,cg12179661,cg16780603,cg00588614,cg13039082,cg16640358
count,456.000000,441.000000,444.000000,444.000000,439.000000,445.000000,442.000000,444.000000,444.000000,445.000000,...,443.000000,445.000000,440.000000,438.000000,439.000000,447.000000,444.000000,449.000000,441.000000,442.000000
mean,64.451754,0.672185,0.474773,0.258354,0.306423,0.595564,0.288657,0.436605,0.409220,0.260792,...,0.178872,0.079003,0.159781,0.315001,0.052955,0.503354,0.748769,0.272942,0.295699,0.328856
std,14.631964,0.077055,0.054078,0.075822,0.068490,0.079845,0.050484,0.037576,0.068441,0.046445,...,0.026149,0.037605,0.030063,0.053531,0.029233,0.039453,0.052084,0.034739,0.028885,0.035468
min,19.000000,0.445097,0.282605,0.067115,0.128342,0.334084,0.177003,0.313451,0.195333,0.166556,...,0.123852,0.009463,0.065345,0.091694,0.008391,0.362170,0.443848,0.180870,0.204703,0.112017
25%,54.000000,0.618232,0.438860,0.204332,0.254861,0.548695,0.254821,0.412552,0.364191,0.231042,...,0.161000,0.054660,0.140273,0.281743,0.032664,0.479161,0.714236,0.247651,0.278145,0.309714
50%,65.000000,0.671475,0.474176,0.254157,0.303910,0.592122,0.283393,0.436484,0.403738,0.253488,...,0.177849,0.070133,0.161703,0.317862,0.045958,0.505584,0.751891,0.272034,0.294440,0.332205
75%,75.250000,0.730840,0.509154,0.303655,0.347685,0.647835,0.311986,0.458404,0.454823,0.284778,...,0.193245,0.096696,0.180514,0.348837,0.067091,0.528347,0.782235,0.296712,0.314815,0.351723
max,101.000000,0.945175,0.685392,0.641456,0.634227,0.892856,0.589594,0.588123,0.755933,0.511116,...,0.379735,0.262035,0.249790,0.508594,0.230947,0.616206,0.889028,0.381865,0.451566,0.421915

In [9]:
import sys
import os

sys.path.append(os.path.abspath(".."))

In [10]:
from src.functions import stratified_split

train_df, val_df = stratified_split(dev_data)
print("Train size:", train_df.shape)
print("Validation size:", val_df.shape)

Train size: (364, 1004)
Validation size: (92, 1004)